## Importing Libraries

In [ ]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

True

In [ ]:
!pip install simpletransformers

Collecting simpletransformers
  Downloading simpletransformers-0.64.3-py3-none-any.whl (250 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.8/250.8 kB 5.2 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (1.23.5)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (2.31.0)
Requirement already satisfied: tqdm>=4.47.0 in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (4.66.1)
Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (2023.6.3)
Collecting transformers>=4.31.0 (from simpletransformers)
  Downloading transformers-4.35.2-py3-none-any.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 33.2 MB/s eta 0:00:00
Collecting datasets (from simpletransformers)
  Downloading datasets-2.15.0-py3-none-any.whl (521 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 521.2/521.2 kB 42.8 MB/s eta 0:00:00
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (1.11.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (1.2.2)
Collecting seqeval (from simpletransformers)
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 5.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tensorboard in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (2.14.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from simpletransformers) (1.5.3)
Collecting tokenizers (from simpletransformers)
  Downloading tokenizers-0.15.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 69.6 MB/s eta 0:00:00
Collecting wandb>=0.10.32 (from simpletransformers)
  Downloading wandb-0.16.0-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 48.2 MB/s eta 0:00:00
Collecting streamlit (from simpletransformers)
  Downloading streamlit-1.28.2-py2.py3-none-any.whl (8.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 74.7 MB/s eta 0:00:00
Collecting sentencepiece (from simpletransformers)
  Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 64.8 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers>=4.31.0->simpletransformers) (3.13.1)
Collecting huggingface-hub<1.0,>=0.16.4 (from transformers>=4.31.0->simpletransformers)
  Downloading huggingface_hub-0.19.4-py3-none-any.whl (311 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.7/311.7 kB 36.9 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.31.0->simpletransformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.31.0->simpletransformers) (6.0.1)
Collecting safetensors>=0.3.1 (from transformers>=4.31.0->simpletransformers)
  Downloading safetensors-0.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 76.5 MB/s eta 0:00:00
Requirement already satisfied: Click!=8.0.0,>=7.1 in /usr/local/lib/python3.10/dist-packages (from wandb>=0.10.32->simpletransformers) (8.1.7)
Collecting GitPython!=3.1.29,>=1.0.0 (from wandb>=0.10.32->simpletransformers)
  Downloading GitPython-3.1.40-py3-none-any.whl (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.6/190.6 kB 25.5 MB/s eta 0:00:00
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb>=0.10.32->simpletransformers) (5.9.5)
Collecting sentry-sdk>=1.0.0 (from wandb>=0.10.32->simpletransformers)
  Downloading sentry_sdk-1.35.0-py2.py3-none-any.whl (248 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.6/248.6 kB 22.7 MB/s eta 0:00:00
Collecting docker-pycreds>=0.4.0 (from wandb>=0.10.32->simpletransformers)
  Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Collecting setproctitle (from wandb>=0.10.32->simpletransformers)
  Downloading setproctitle-1.3.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from wandb>=0.10.32->simpletransformers) (67.7.2)
Requirement already satisfied: appdirs>=1.4.3 in /usr/local/lib/python3.10/dist-packages (from wandb>=0.10.32->simpletransformers) (1.4.4)
Requirement already satisfied: protobuf!=4.21.0,<5,>=3.19.0 in /usr/local/lib/python3.10/dist-packages (from wandb>=0.10.32->simpletransformers) (3.20.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->simpletransformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->simpletransformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->simpletransformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->simpletransformers) (2023.7.22)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets->simpletransformers) (9.0.0)
Collecting pyarrow-hotfix (from datasets->simpletransformers)
  Downloading pyarrow_hotfix-0.5-py3-none-any.whl (7.8 kB)
Collecting dill<0.3.8,>=0.3.0 (from datasets->simpletransformers)
  Downloading dill-0.3.7-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 16.9 MB/s eta 0:00:00
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets->simpletransformers) (3.4.1)
Collecting multiprocess (from datasets->simpletransformers)
  Downloading multiprocess-0.70.15-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 17.7 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]<=2023.10.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from datasets->simpletransformers) (2023.6.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets->simpletransformers) (3.8.6)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->simpletransformers) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->simpletransformers) (2023.3.post1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->simpletransformers) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->simpletransformers) (3.2.0)
Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (4.2.2)
Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit->simpletransformers) (1.4)
Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (5.3.2)
Requirement already satisfied: importlib-metadata<7,>=1.4 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (6.8.0)
Requirement already satisfied: pillow<11,>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (9.4.0)
Requirement already satisfied: rich<14,>=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (13.6.0)
Requirement already satisfied: tenacity<9,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (8.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (4.5.0)
Requirement already satisfied: tzlocal<6,>=1.1 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (5.2)
Collecting validators<1,>=0.2 (from streamlit->simpletransformers)
  Downloading validators-0.22.0-py3-none-any.whl (26 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit->simpletransformers)
  Downloading pydeck-0.8.1b0-py2.py3-none-any.whl (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 100.6 MB/s eta 0:00:00
Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit->simpletransformers) (6.3.2)
Collecting watchdog>=2.1.5 (from streamlit->simpletransformers)
  Downloading watchdog-3.0.0-py3-none-manylinux2014_x86_64.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 11.4 MB/s eta 0:00:00
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (1.59.2)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (2.17.3)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (3.5.1)
Requirement already satisfied: six>1.9 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (1.16.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard->simpletransformers) (3.0.1)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit->simpletransformers) (0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit->simpletransformers) (3.1.2)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit->simpletransformers) (4.19.2)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit->simpletransformers) (0.12.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->simpletransformers) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->simpletransformers) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->simpletransformers) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->simpletransformers) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->simpletransformers) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->simpletransformers) (1.3.1)
Collecting gitdb<5,>=4.0.1 (from GitPython!=3.1.29,>=1.0.0->wandb>=0.10.32->simpletransformers)
  Downloading gitdb-4.0.11-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 7.7 MB/s eta 0:00:00
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard->simpletransformers) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard->simpletransformers) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard->simpletransformers) (1.3.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata<7,>=1.4->streamlit->simpletransformers) (3.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit->simpletransformers) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit->simpletransformers) (2.16.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard->simpletransformers) (2.1.3)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->GitPython!=3.1.29,>=1.0.0->wandb>=0.10.32->simpletransformers)
  Downloading smmap-5.0.1-py3-none-any.whl (24 kB)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit->simpletransformers) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit->simpletransformers) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit->simpletransformers) (0.12.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit->simpletransformers) (0.1.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->simpletransformers) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard->simpletransformers) (3.2.2)
Building wheels for collected packages: seqeval
  Building wheel for seqeval (setup.py) ... done
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16161 sha256=8331351020288a637620f76596efd53f2356c908bfb963400dacaab958642dec
  Stored in directory: /root/.cache/pip/wheels/1a/67/4a/ad4082dd7dfc30f2abfe4d80a2ed5926a506eb8a972b4767fa
Successfully built seqeval
Installing collected packages: sentencepiece, watchdog, validators, smmap, setproctitle, sentry-sdk, safetensors, pyarrow-hotfix, docker-pycreds, dill, pydeck, multiprocess, huggingface-hub, gitdb, tokenizers, seqeval, GitPython, wandb, transformers, datasets, streamlit, simpletransformers
Successfully installed GitPython-3.1.40 datasets-2.15.0 dill-0.3.7 docker-pycreds-0.4.0 gitdb-4.0.11 huggingface-hub-0.19.4 multiprocess-0.70.15 pyarrow-hotfix-0.5 pydeck-0.8.1b0 safetensors-0.4.0 sentencepiece-0.1.99 sentry-sdk-1.35.0 seqeval-1.2.2 setproctitle-1.3.3 simpletransformers-0.64.3 smmap-5.0.1 streamlit-1.28.2 tokenizers-0.15.0 transformers-4.35.2 validators-0.22.0 wandb-0.16.0 watchdog-3.0.0

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.35.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.19.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.15.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2023.7.22)

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
!pip install textblob

Requirement already satisfied: textblob in /usr/local/lib/python3.10/dist-packages (0.17.1)
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.10/dist-packages (from textblob) (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->textblob) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->textblob) (2024.5.15)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->textblob) (4.66.4)

In [ ]:
from textblob import TextBlob

In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer as sia
from tqdm.notebook import tqdm

## **Dataset Cleaning**

Reading CSV File

In [ ]:
df = pd.read_csv("/content/raw_data.csv")

In [ ]:
df.head()

,Sno,Date,Headline,Covid,Sentiment,Description,Image,Source
0,0,2020-04-29,"Coronavirus cases reach 2,438 in Rajasthan; 81...",1,0,Rajasthan on Wednesday reported 74 new coronav...,https://static.inshorts.com/inshorts/images/v1...,http://www.rajswasthya.nic.in/?utm_campaign=fu...
1,1,2020-04-29,"Coronavirus cases in Delhi surge to 3,439 afte...",1,0,The total number of coronavirus cases in Delhi...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/shemin_joy/status/12555489...
2,2,2020-04-30,"Anguished, I'll always recall our interactions...",0,1,"Condoling the demise of actor Rishi Kapoor, PM...",https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/narendramodi/status/125573...
3,3,2020-04-30,It's a terrible week for Indian cinema: Rahul ...,0,0,Congress leader Rahul Gandhi condoled Rishi Ka...,https://static.inshorts.com/inshorts/images/v1...,https://zeenews.india.com/india/politicians-mo...
4,4,2020-04-30,Delhi Police perform 'parikrama' of AIIMS to t...,1,1,As a sign of respect for healthcare profession...,https://static.inshorts.com/inshorts/images/v1...,https://zeenews.india.com/india/delhi-police-p...

# Checking for null and duplicates

no nulls and duplicates

In [ ]:
df.isnull().sum()

Sno            0
Date           0
Headline       0
Covid          0
Sentiment      0
Description    0
Image          0
Source         0
dtype: int64

In [ ]:
df.duplicated().sum()

0

# Removing columns that are not needed

In [ ]:
df.columns

Index(['Sno', 'Date', 'Headline', 'Covid', 'Sentiment', 'Description', 'Image',
       'Source'],
      dtype='object')

In [ ]:
df = df.drop(["Sno", "Covid", "Description", "Image", "Source"], axis = 1)

In [ ]:
df.shape

(4072, 3)

In [ ]:
df.columns

Index(['Date', 'Headline', 'Sentiment'], dtype='object')

cleaned dataset

## VADER model

In [ ]:
sid = sia()

few examples

In [ ]:
sid.polarity_scores("i am happy!")

{'neg': 0.0, 'neu': 0.2, 'pos': 0.8, 'compound': 0.6114}

In [ ]:
sid.polarity_scores("i am devastated")

{'neg': 0.8, 'neu': 0.2, 'pos': 0.0, 'compound': -0.6124}

 Polarity scores for dataset

In [ ]:
#Run the polarity scores on the entire dataset
res = {}
for i, row in tqdm(df.iterrows(), total = len(df)):
  text = row['Headline']
  date = row['Date']
  res[date] = sid.polarity_scores(text)

  0%|          | 0/4072 [00:00<?, ?it/s]

In [ ]:
vaders = pd.DataFrame(res).T
vaders = vaders.reset_index().rename(columns = {'index' : 'Date'})
vaders = vaders.merge(df, how = 'left')

In [ ]:
vaders.head()

,Date,neg,neu,pos,compound,Sno,Headline,Covid,Sentiment,Description,Image,Source
0,2020-04-29,0.174,0.826,0.0,-0.2732,0,"Coronavirus cases reach 2,438 in Rajasthan; 81...",1,0,Rajasthan on Wednesday reported 74 new coronav...,https://static.inshorts.com/inshorts/images/v1...,http://www.rajswasthya.nic.in/?utm_campaign=fu...
1,2020-04-29,0.174,0.826,0.0,-0.2732,1,"Coronavirus cases in Delhi surge to 3,439 afte...",1,0,The total number of coronavirus cases in Delhi...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/shemin_joy/status/12555489...
2,2020-04-29,0.174,0.826,0.0,-0.2732,19,"Man burnt alive, 7 houses and temple gutted in...",0,0,A 35-year-old man was burnt alive while two pe...,https://static.inshorts.com/inshorts/images/v1...,https://covid-positive-news.herokuapp.com
3,2020-04-29,0.174,0.826,0.0,-0.2732,24,81 coronavirus patients recover in Gautam Budd...,1,1,Gautam Buddha Nagar District Magistrate Suhas ...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/dmgbnagar/status/125545866...
4,2020-04-29,0.174,0.826,0.0,-0.2732,25,Colleges to reopen for old students from Aug 1...,1,1,The UGC today said that the 2020-21 academic s...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/TimesNow/status/1255507208...

In [ ]:
vaders['compound']

0      -0.2732
1      -0.2732
2      -0.2732
3      -0.2732
4      -0.2732
         ...
4067   -0.2263
4068   -0.2263
4069   -0.2263
4070   -0.2263
4071   -0.2263
Name: compound, Length: 4072, dtype: float64

In [ ]:
vaders['Sentiment-score'] = vaders['Sentiment'].apply(lambda c : 'pos' if c > 0 else 'neg')
vaders.head()

,Date,neg,neu,pos,compound,Sno,Headline,Covid,Sentiment,Description,Image,Source,Sentiment-score
0,2020-04-29,0.174,0.826,0.0,-0.2732,0,"Coronavirus cases reach 2,438 in Rajasthan; 81...",1,0,Rajasthan on Wednesday reported 74 new coronav...,https://static.inshorts.com/inshorts/images/v1...,http://www.rajswasthya.nic.in/?utm_campaign=fu...,neg
1,2020-04-29,0.174,0.826,0.0,-0.2732,1,"Coronavirus cases in Delhi surge to 3,439 afte...",1,0,The total number of coronavirus cases in Delhi...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/shemin_joy/status/12555489...,neg
2,2020-04-29,0.174,0.826,0.0,-0.2732,19,"Man burnt alive, 7 houses and temple gutted in...",0,0,A 35-year-old man was burnt alive while two pe...,https://static.inshorts.com/inshorts/images/v1...,https://covid-positive-news.herokuapp.com,neg
3,2020-04-29,0.174,0.826,0.0,-0.2732,24,81 coronavirus patients recover in Gautam Budd...,1,1,Gautam Buddha Nagar District Magistrate Suhas ...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/dmgbnagar/status/125545866...,pos
4,2020-04-29,0.174,0.826,0.0,-0.2732,25,Colleges to reopen for old students from Aug 1...,1,1,The UGC today said that the 2020-21 academic s...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/TimesNow/status/1255507208...,pos

In [ ]:
vaders['Compound-score'] = vaders['compound'].apply(lambda c : 'pos' if c > 0 else 'neg')
vaders.head()

,Date,neg,neu,pos,compound,Sno,Headline,Covid,Sentiment,Description,Image,Source,Sentiment-score,Compound-score
0,2020-04-29,0.174,0.826,0.0,-0.2732,0,"Coronavirus cases reach 2,438 in Rajasthan; 81...",1,0,Rajasthan on Wednesday reported 74 new coronav...,https://static.inshorts.com/inshorts/images/v1...,http://www.rajswasthya.nic.in/?utm_campaign=fu...,neg,neg
1,2020-04-29,0.174,0.826,0.0,-0.2732,1,"Coronavirus cases in Delhi surge to 3,439 afte...",1,0,The total number of coronavirus cases in Delhi...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/shemin_joy/status/12555489...,neg,neg
2,2020-04-29,0.174,0.826,0.0,-0.2732,19,"Man burnt alive, 7 houses and temple gutted in...",0,0,A 35-year-old man was burnt alive while two pe...,https://static.inshorts.com/inshorts/images/v1...,https://covid-positive-news.herokuapp.com,neg,neg
3,2020-04-29,0.174,0.826,0.0,-0.2732,24,81 coronavirus patients recover in Gautam Budd...,1,1,Gautam Buddha Nagar District Magistrate Suhas ...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/dmgbnagar/status/125545866...,pos,neg
4,2020-04-29,0.174,0.826,0.0,-0.2732,25,Colleges to reopen for old students from Aug 1...,1,1,The UGC today said that the 2020-21 academic s...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/TimesNow/status/1255507208...,pos,neg

In [ ]:
print(confusion_matrix(vaders['Sentiment-score'], vaders['Compound-score']))

[[1897  845]
 [ 989  341]]

In [ ]:
# VADER Result
print(classification_report(vaders['Sentiment-score'], vaders['Compound-score']))

              precision    recall  f1-score   support

         neg       0.66      0.69      0.67      2742
         pos       0.29      0.26      0.27      1330

    accuracy                           0.55      4072
   macro avg       0.47      0.47      0.47      4072
weighted avg       0.54      0.55      0.54      4072

In [ ]:
accuracy_score(vaders['Sentiment-score'], vaders['Compound-score'])

0.5496070726915521

## Roberta Model

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
train, test = train_test_split(df, test_size = 0.2)

In [ ]:
from simpletransformers.classification import ClassificationModel

model = ClassificationModel('roberta', f"cardiffnlp/twitter-roberta-base-sentiment", num_labels = 3, args =
 {
    'reprocess_input_data' : True,
    'overwrite_output_dir' : True
  },
                            use_cuda = False)

(…)-base-sentiment/resolve/main/config.json:   0%|          | 0.00/747 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

(…)a-base-sentiment/resolve/main/vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

(…)a-base-sentiment/resolve/main/merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

(…)ent/resolve/main/special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

In [ ]:
trainr_df = pd.DataFrame({'text' : train['Headline'].replace(r'\n', ' ', regex = True), 'label' : train['Sentiment']})
evalr_df = pd.DataFrame({'text' : test['Headline'].replace(r'\n', ' ', regex = True), 'label' : test['Sentiment']})

In [ ]:
model.train_model(trainr_df)

/usr/local/lib/python3.10/dist-packages/simpletransformers/classification/classification_model.py:612: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  warnings.warn(

  0%|          | 0/3257 [00:00<?, ?it/s]

Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 0 of 1:   0%|          | 0/408 [00:00<?, ?it/s]

(408, 0.45494529815828977)

In [ ]:
result, model_outputs, wrong_predictions = model.eval_model(evalr_df)

/usr/local/lib/python3.10/dist-packages/simpletransformers/classification/classification_model.py:1454: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  warnings.warn(

  0%|          | 0/815 [00:00<?, ?it/s]

Running Evaluation:   0%|          | 0/102 [00:00<?, ?it/s]

In [ ]:
result

{'mcc': 0.7302354577304353, 'eval_loss': 0.3317710743559634}

In [ ]:
model_outputs

array([[ 1.42330563,  2.71583414, -4.74672127],
       [-0.55231309,  3.34715343, -3.09735751],
       [ 3.49487925,  1.12124646, -4.98806095],
       ...,
       [-0.48252428,  3.44703436, -3.31117988],
       [ 1.49853683,  2.64936495, -4.7543745 ],
       [ 1.41854262,  2.69802332, -4.59067249]])

In [ ]:
lst = []
for arr in model_outputs:
  lst.append(np.argmax(arr))

In [ ]:
true = evalr_df['label'].tolist()
predicted = lst

In [ ]:
import sklearn
mat = sklearn.metrics.confusion_matrix(true, predicted)
mat

array([[460,  69],
       [ 35, 251]])

In [ ]:
#Roberta Result
sklearn.metrics.accuracy_score(true, predicted)

0.8723926380368098

In [ ]:
sklearn.metrics.f1_score(true, predicted)

0.8283828382838283

## BERT Model

In [ ]:
# Test and Train the data
train, test = train_test_split(df, test_size = 0.2)

Building a model

In [ ]:
from simpletransformers.classification import ClassificationModel

model = ClassificationModel('bert', 'bert-base-cased', num_labels = 3, args =
 {
    'reprocess_input_data' : True,
    'overwrite_output_dir' : True
  },
                            use_cuda = False)

Downloading (…)lve/main/config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Downloading (…)okenizer_config.json:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading (…)/main/tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [ ]:
trainb_df = pd.DataFrame({'text' : train['Headline'].replace(r'\n', ' ', regex = True), 'label' : train['Sentiment']})
evalb_df = pd.DataFrame({'text' : test['Headline'].replace(r'\n', ' ', regex = True), 'label' : test['Sentiment']})

In [ ]:
model.train_model(trainb_df)

  0%|          | 0/3257 [00:00<?, ?it/s]

Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 0 of 1:   0%|          | 0/408 [00:00<?, ?it/s]

(408, 0.45020649556810144)

In [ ]:
result, model_outputs, wrong_predictions = model.eval_model(evalb_df)

  0%|          | 0/815 [00:00<?, ?it/s]

Running Evaluation:   0%|          | 0/102 [00:00<?, ?it/s]

In [ ]:
result

{'mcc': 0.6382488048800944, 'eval_loss': 0.4186269024606137}

In [ ]:
model_outputs

array([[ 3.86278844, -0.84099877, -2.96068192],
       [ 3.1927228 ,  0.41430053, -3.17711639],
       [ 3.03764844,  1.0657742 , -3.58570981],
       ...,
       [ 3.45069766,  0.40950403, -3.55495739],
       [ 3.99971533, -0.81417567, -3.0009048 ],
       [ 1.43140972,  2.16726494, -3.06155849]])

In [ ]:
lst = []
for arr in model_outputs:
  lst.append(np.argmax(arr))

In [ ]:
true = evalb_df['label'].tolist()
predicted = lst

In [ ]:
import sklearn
mat = sklearn.metrics.confusion_matrix(true, predicted)
mat

array([[473,  82],
       [ 51, 209]])

In [ ]:
sklearn.metrics.classification_report(true, predicted, target_names = ['positive', 'negative'])

'              precision    recall  f1-score   support\n\n    positive       0.90      0.85      0.88       555\n    negative       0.72      0.80      0.76       260\n\n    accuracy                           0.84       815\n   macro avg       0.81      0.83      0.82       815\nweighted avg       0.84      0.84      0.84       815\n'

In [ ]:
#BERT Result
sklearn.metrics.accuracy_score(true, predicted)

0.8368098159509203

In [ ]:
sklearn.metrics.f1_score(true, predicted)

0.7586206896551725

## TextBlob Model

In [ ]:
df['polarity_score'] = df['Headline'].apply(lambda s: TextBlob(s).sentiment.polarity)
df.head()

,Sno,Date,Headline,Covid,Sentiment,Description,Image,Source,polarity_score
0,0,2020-04-29,"Coronavirus cases reach 2,438 in Rajasthan; 81...",1,0,Rajasthan on Wednesday reported 74 new coronav...,https://static.inshorts.com/inshorts/images/v1...,http://www.rajswasthya.nic.in/?utm_campaign=fu...,0.000000
1,1,2020-04-29,"Coronavirus cases in Delhi surge to 3,439 afte...",1,0,The total number of coronavirus cases in Delhi...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/shemin_joy/status/12555489...,0.136364
2,2,2020-04-30,"Anguished, I'll always recall our interactions...",0,1,"Condoling the demise of actor Rishi Kapoor, PM...",https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/narendramodi/status/125573...,0.000000
3,3,2020-04-30,It's a terrible week for Indian cinema: Rahul ...,0,0,Congress leader Rahul Gandhi condoled Rishi Ka...,https://static.inshorts.com/inshorts/images/v1...,https://zeenews.india.com/india/politicians-mo...,-1.000000
4,4,2020-04-30,Delhi Police perform 'parikrama' of AIIMS to t...,1,1,As a sign of respect for healthcare profession...,https://static.inshorts.com/inshorts/images/v1...,https://zeenews.india.com/india/delhi-police-p...,0.000000

In [ ]:
import sklearn

In [ ]:
df['Sentiment-score'] = df['Sentiment'].apply(lambda c : 'pos' if c > 0 else 'neg')
df.head()

,Sno,Date,Headline,Covid,Sentiment,Description,Image,Source,polarity_score,Sentiment-score
0,0,2020-04-29,"Coronavirus cases reach 2,438 in Rajasthan; 81...",1,0,Rajasthan on Wednesday reported 74 new coronav...,https://static.inshorts.com/inshorts/images/v1...,http://www.rajswasthya.nic.in/?utm_campaign=fu...,0.000000,neg
1,1,2020-04-29,"Coronavirus cases in Delhi surge to 3,439 afte...",1,0,The total number of coronavirus cases in Delhi...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/shemin_joy/status/12555489...,0.136364,neg
2,2,2020-04-30,"Anguished, I'll always recall our interactions...",0,1,"Condoling the demise of actor Rishi Kapoor, PM...",https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/narendramodi/status/125573...,0.000000,pos
3,3,2020-04-30,It's a terrible week for Indian cinema: Rahul ...,0,0,Congress leader Rahul Gandhi condoled Rishi Ka...,https://static.inshorts.com/inshorts/images/v1...,https://zeenews.india.com/india/politicians-mo...,-1.000000,neg
4,4,2020-04-30,Delhi Police perform 'parikrama' of AIIMS to t...,1,1,As a sign of respect for healthcare profession...,https://static.inshorts.com/inshorts/images/v1...,https://zeenews.india.com/india/delhi-police-p...,0.000000,pos

In [ ]:
df['polarity-score'] = df['polarity_score'].apply(lambda c : 'pos' if c > 0 else 'neg')
df.head()

,Sno,Date,Headline,Covid,Sentiment,Description,Image,Source,polarity_score,Sentiment-score,polarity-score
0,0,2020-04-29,"Coronavirus cases reach 2,438 in Rajasthan; 81...",1,0,Rajasthan on Wednesday reported 74 new coronav...,https://static.inshorts.com/inshorts/images/v1...,http://www.rajswasthya.nic.in/?utm_campaign=fu...,0.000000,neg,neg
1,1,2020-04-29,"Coronavirus cases in Delhi surge to 3,439 afte...",1,0,The total number of coronavirus cases in Delhi...,https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/shemin_joy/status/12555489...,0.136364,neg,pos
2,2,2020-04-30,"Anguished, I'll always recall our interactions...",0,1,"Condoling the demise of actor Rishi Kapoor, PM...",https://static.inshorts.com/inshorts/images/v1...,https://twitter.com/narendramodi/status/125573...,0.000000,pos,neg
3,3,2020-04-30,It's a terrible week for Indian cinema: Rahul ...,0,0,Congress leader Rahul Gandhi condoled Rishi Ka...,https://static.inshorts.com/inshorts/images/v1...,https://zeenews.india.com/india/politicians-mo...,-1.000000,neg,neg
4,4,2020-04-30,Delhi Police perform 'parikrama' of AIIMS to t...,1,1,As a sign of respect for healthcare profession...,https://static.inshorts.com/inshorts/images/v1...,https://zeenews.india.com/india/delhi-police-p...,0.000000,pos,neg

In [ ]:
print(confusion_matrix(df['Sentiment-score'], df['polarity-score']))

[[2169  573]
 [1041  289]]

In [ ]:
#TextBlob Result
print(classification_report(df['Sentiment-score'], df['polarity-score']))

              precision    recall  f1-score   support

         neg       0.68      0.79      0.73      2742
         pos       0.34      0.22      0.26      1330

    accuracy                           0.60      4072
   macro avg       0.51      0.50      0.50      4072
weighted avg       0.56      0.60      0.58      4072

In [ ]:
accuracy_score(df['Sentiment-score'], df['polarity-score'])

0.6036345776031434